### ISSUE TITLE
Separate backend and frontend into different crates in same workspace

### ISSUE THREAD

**Issue by Boscop** [saschagrunert/webapp.rs#10]
It would be cleaner to read when backend and frontend are split into separate crates (possibly both depending on a common crate) in the same [workspace](https://doc.rust-lang.org/book/second-edition/ch14-03-cargo-workspaces.html).

**Comment by saschagrunert** [comment]
Yes, I will consider switching to rust workspaces and a more coupled dependency management.

**Comment by saschagrunert** [comment]
This will be done in #9

**Comment by saschagrunert** [comment]
Solved with #9

**Comment by NobbZ** [comment]
But the old crate is still there… This is a bit confusing…

Which part of the repository is still relevant? What is old stuff? Are both, worksapces and the main crate still relevant? Is this even valid, having a crate **and** a workspace at the toplevel?

**Comment by saschagrunert** [comment]
Every part of the repository is still relevant, the main structure looks like this now:

- Main Crate, used by both backend and frontend
  - Backend
  - Frontend

So its some kind of tree dependency structure now. :)

**Comment by NobbZ** [comment]
Oh, I thought I'd seen the same file in multiple places, but now I realized I looked at different commits.

Still, I think it would be less confusing if you were putting the common/shared parts in another crate **not** at the top level, I think that would make the differences more clear.

**Comment by saschagrunert** [comment]
Alright thank you very much for the feedback, I will consider the approach you mentioned.
