### ISSUE TITLE
Auto reconnect the ws connection

### ISSUE THREAD

**Issue by Boscop** [saschagrunert/webapp.rs#11]
It would be useful to auto reconnect the ws connection in case it got disconnected (e.g. due to network issues).

**Comment by saschagrunert** [comment]
I guess this would be a nice addition.

**Comment by saschagrunert** [comment]
Will be fixed with #9

**Comment by saschagrunert** [comment]
Solved with #9, where plain HTTP is used instead of a websocket connection.
