### ISSUE TITLE
Consider switching to CBOR

### ISSUE THREAD

**Issue by saschagrunert** [saschagrunert/webapp.rs#12]
The benefit would be to use serde and its derivations as well as using the same data types for the protocol and diesel models.

A disadvantage is that we loose the versioning and a bit of performance.

#9 contains a experimental implementation

**Comment by Deedasmi** [comment]
I'd love to see a benchmark with your notes on CBOR vs capnproto!

**Comment by saschagrunert** [comment]
Solved with #9, where CBOR is the current communication standard

**Comment by pickfire** [comment]
Any performance decrease after switching to CBOR? @saschagrunert I am interested to hear a blog post about it.

**Comment by saschagrunert** [comment]
Actually not. :) But I am currently evaluating the new architecture and will release a new blog post soon.
