### ISSUE TITLE
error: no such subcommand: `web`

### ISSUE THREAD

**Issue by Notmeor** [saschagrunert/webapp.rs#123]
When execute `make run-frontend` in the cloned repo root, it complains:
```
error: no such subcommand: `web`

	Did you mean `new`?

Makefile:97: recipe for target 'run-frontend' failed
make: *** [run-frontend] Error 101
```
I'm on Ubuntu 16.04

**Comment by Notmeor** [comment]
My bad. Have to install cargo-web first.

**Comment by saschagrunert** [comment]
Yep, nevertheless thanks for trying out the project. :)

**Comment by non-binary** [comment]
@saschagrunert @Notmeor What did you do to put it in your path? I'm still getting the error. Maybe this is a basic thing. :c Please help!
