### ISSUE TITLE
What would be required to run the backend and postgresql in different VM's instead of podman or docker.

### ISSUE THREAD

**Issue by xekon** [saschagrunert/webapp.rs#1600]
I would like to try running the backend in its own VM, the frontend in its own VM, and postgresql in its own VM.

I only just today starting reading about and working with Rust. I found this project listed here: https://github.com/actix/examples

I only use docker when necessary, however I did try to use podman initially just so that I could try and test things, unfortunately it did not work:

```
root@Web:~/webapp# make deploy
Error: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver
make: *** [Makefile:59: deploy] Error 125
```

I am currently looking at all the files included with this project and trying to get understanding of how it all fits together so that I can separate the backend and frontend as separate applications that run natively without the need for podman.

**Comment by saschagrunert** [comment]
Hey :wave:, yeah right now the project is only build to run on container runtimes. :upside_down_face:

**Comment by xekon** [comment]
Thanks, I am going to try an adapt some of the code to run without using container runtimes. Thank you for the quick response.
