### ISSUE TITLE
Factoring out the RouterService into its own crate?

### ISSUE THREAD

**Issue by Boscop** [saschagrunert/webapp.rs#23]
I think it would make a lot of sense to factor out the `RouterService` into its own crate, so that it can be used by other apps.

I think a good API would allow it to be used as conveniently and type-safe as this:

https://github.com/parsonsmatt/purescript-routing-example/blob/master/src/Router.purs

[purescript-routing guide](https://github.com/slamdata/purescript-routing/blob/master/GUIDE.md#a-guide-to-purescript-routing)

[blog post about the above example of using purescript-routing](http://www.parsonsmatt.org/2015/10/22/purescript_router.html)

**Comment by saschagrunert** [comment]
Yes, I think this would be a feasible addition. I can do that in the near future.
