### ISSUE TITLE
Without postgresql, with empty State, unpack_cbor results in E0284

### ISSUE THREAD

**Issue by PAStheLoD** [saschagrunert/webapp.rs#25]
Hello,

First of all thanks for sharing this wonderful project with the community!

And please close this ticket if this is the wrong place to ask this question.

So, after unceremoniously commenting out a lot of database related stuff, after changing State (because an empty State<T> wouldn't compile due to unused type parameter) and all its use sites, I got stuck with this:

```
error[E0284]: type annotations required: cannot resolve `<_ as actix::Actor>::Context == _`                                                                                                   
  --> backend/src/http/login_credentials/mod.rs:21:33                                                                                                                                         
   |                                                                                                                                                                                          
21 |     let (request_clone, cbor) = unpack_cbor(http_request);                                                                                                                               
   |                                 ^^^^^^^^^^^                                                                                                                                              
     
```

```
  /// Cbor unpacking helper, also returns a clone of the request reference
  pub fn unpack_cbor<A, D, M>(
--    http_request: &HttpRequest<State<A>>,
--) -> (HttpRequest<State<A>>, FromErr<CborRequest<D>, Error>)
++    http_request: &HttpRequest<State>,
++) -> (HttpRequest<State>, FromErr<CborRequest<D>, Error>)
  where
      M: Message,
      D: DeserializeOwned + 'static,
```

```
  /// Shared mutable application state
--pub struct State<T>
--where
--    T: Actor,
--{
--    /// The database connection
--    pub database: Addr<T>,
--}
++pub struct State;
```

And I've replaced the CreateSession, UpdateSession, DeleteSession structs, I don't know if it matters.

```
++
++
++use actix::prelude::*;
++use failure::Fallible;
++use webapp::{protocol::model::Session};
++
++pub struct Data(pub String);
++
++impl Message for Data {
++    type Result = Fallible<Session>;
++}
++
++impl From<String> for Data {
++    fn from(s: String) -> Data {
++       Data(s)
++    }
++}
++
```

This is on nightly-1.30.

Thanks!

**Comment by saschagrunert** [comment]
Hi, thank you very much for the request! If would be good if you could provide a full example (maybe a git repository) containing your current work for debugging purposes. One possible problem could be that you did not remove the generic parameter `A` from the `unpack_cbor()` function.

**Comment by PAStheLoD** [comment]
Thanks for the rapid response!

Yes, I haven't touched the rest of unpack, as it seems to be rather daunting.

https://github.com/PAStheLoD/webapp.rs  shows the current state.

If I remove A, then Rust cannot infer M. 

```
error[E0282]: type annotations needed                                                                                                                                                         
  --> backend/src/http/login_credentials/mod.rs:21:33                                                                                                                                         
   |                                                                                                                                                                                          
21 |     let (request_clone, cbor) = unpack_cbor(http_request);                                                                                                                               
   |                                 ^^^^^^^^^^^ cannot infer type for `M`                                                                                                                    
       ```

**Comment by saschagrunert** [comment]
The request clone part can also be removed since it is not used any more. The compiler cannot infer the type because its generic and not further used. I updated a working version of your modification within the https://github.com/saschagrunert/webapp.rs/tree/nostate-demo branch. If you have no further questions feel free to close this issue. :)

**Comment by PAStheLoD** [comment]
Wow, thanks! I have a lot of questions about how did you come up with the required trait bounds and stuff for unpack_cbor initially. (But of course I don't think you have to educate random strangers on the 'net about Rust, and it's not strictly relevant to the original question, so I'm closing this, but I'd be very happy read about the aforementioned typing process.)

**Comment by saschagrunert** [comment]
You’re always welcome to open new issues with further questions if you want to. 🤗
