### ISSUE TITLE
Does not work on Firefox

### ISSUE THREAD

**Issue by Ticsmtc** [saschagrunert/webapp.rs#639]
Dont work properly on firefox. But work prefect on Chrome.

My system is Debian 10 .
Firefox version : 68.2.0esr 
Chrome version : 78.0.3904.108

This is how I run the project
`git clone https://github.com/saschagrunert/webapp.rs.git && cd webapp.rs`
Change "podman" to "docker" in `Makefile`
 I've installed all the dependencies。
`make run-app`

Access to `localhost:30080` and try to login , Chrome successed , Firefox just return a 408 page .

Here is what i found in Firefox Console : 

![issue](https://user-images.githubusercontent.com/16485128/69989973-c34f3780-157f-11ea-8b32-052be9087f41.png)

This is really weird, because everything works fine on Chrome, but not on Firefox. And I can't solve the problem by reading the error message.

**Comment by saschagrunert** [comment]
@Ticsmtc thank you for the report, this looks interesting and might be related to some content type handling of Firefox. I'll check.

**Comment by Ticsmtc** [comment]
Thanks a lot !
I switch to firefox-nightly version now , and problem soloved . But still have the same problem on my firefox-esr version .  Never mind, i mainly use this project for studying , i think i can let it go . 

Again ! Thank you !
